/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.50
 * Generated at: 2026-04-21 03:33:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.kho;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;
import model.TaiKhoan;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/header.jsp", Long.valueOf(1776742045465L));
    _jspx_dependants.put("/WEB-INF/footer.jsp", Long.valueOf(1776742045465L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("model.TaiKhoan");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
 String ctx = request.getContextPath(); 
      out.write('\n');
      out.write('\n');
      out.write('\n');

    String pageTitle = (String) request.getAttribute("pageTitle");
    String activeNav = (String) request.getAttribute("activeNav");
    if (pageTitle == null) pageTitle = "Quản lý kho hàng";
    if (activeNav  == null) activeNav  = "";

    TaiKhoan _u   = (TaiKhoan) session.getAttribute("user");
    String _hoTen = (_u != null) ? _u.getHoTen()      : "";
    String _role  = (_u != null) ? _u.getVaiTro()      : "";
    String _label = (_u != null) ? _u.getVaiTroLabel() : "";
    String _av    = (_hoTen.length() > 0) ? String.valueOf(_hoTen.charAt(0)) : "U";
    String _ctx   = request.getContextPath();

    String _flash = (String) session.getAttribute("flash");
    if (_flash != null) session.removeAttribute("flash");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"vi\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>");
      out.print( pageTitle );
      out.write("</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( _ctx );
      out.write("/css/style.css\">\n");
      out.write("    <style>\n");
      out.write("        .nav-item.active {\n");
      out.write("            background: #1e293b !important;\n");
      out.write("            color: #f8fafc !important;\n");
      out.write("            border-left: 3px solid #3b82f6 !important;\n");
      out.write("        }\n");
      out.write("        .flash-msg { padding:12px 18px; border-radius:8px; margin-bottom:16px; font-weight:600; font-size:14px; }\n");
      out.write("        .flash-ok  { background:#dcfce7; border:1px solid #86efac; color:#16a34a; }\n");
      out.write("        .flash-err { background:#fee2e2; border:1px solid #fca5a5; color:#dc2626; }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"wrapper\">\n");
      out.write("\n");
      out.write("<aside class=\"sidebar\">\n");
      out.write("    <div class=\"sidebar-logo\">\n");
      out.write("        <div class=\"icon\">&#127981;</div>\n");
      out.write("        <div>\n");
      out.write("            <div class=\"title\">Quản lý kho hàng</div>\n");
      out.write("            <div class=\"role\">");
      out.print( _label );
      out.write("</div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <nav class=\"sidebar-nav\">\n");
      out.write("\n");
      out.write("        ");
 if ("MUA_HANG".equals(_role)) { 
      out.write("\n");
      out.write("            <a href=\"");
      out.print( _ctx );
      out.write("/muahang/dashboard\" class=\"nav-item ");
      out.print( "MUA_HANG_DASH".equals(activeNav)?"active":"" );
      out.write("\"><span class=\"ni\">&#128722;</span> Đơn mua hàng</a>\n");
      out.write("            <a href=\"");
      out.print( _ctx );
      out.write("/muahang/ncc\"       class=\"nav-item ");
      out.print( "MUA_HANG_NCC".equals(activeNav)?"active":"" );
      out.write("\"><span class=\"ni\">&#127970;</span> Nhà cung cấp</a>\n");
      out.write("            <a href=\"");
      out.print( _ctx );
      out.write("/muahang/taomoi\"    class=\"nav-item ");
      out.print( "MUA_HANG_TAO".equals(activeNav)?"active":"" );
      out.write("\"><span class=\"ni\">&#10133;</span> Tạo đơn mới</a>\n");
      out.write("\n");
      out.write("        ");
 } else if ("KHO".equals(_role)) { 
      out.write("\n");
      out.write("            <a href=\"");
      out.print( _ctx );
      out.write("/kho/dashboard\"  class=\"nav-item ");
      out.print( "KHO_DASH".equals(activeNav)?"active":"" );
      out.write("\"><span class=\"ni\">&#128202;</span> Tổng quan kho</a>\n");
      out.write("            <a href=\"");
      out.print( _ctx );
      out.write("/kho/nhaphang\"   class=\"nav-item ");
      out.print( "KHO_NHAP".equals(activeNav)?"active":"" );
      out.write("\"><span class=\"ni\">&#128229;</span> Nhập hàng</a>\n");
      out.write("            <a href=\"");
      out.print( _ctx );
      out.write("/kho/xuathang\"   class=\"nav-item ");
      out.print( "KHO_XUAT".equals(activeNav)?"active":"" );
      out.write("\"><span class=\"ni\">&#128228;</span> Xuất hàng</a>\n");
      out.write("            <a href=\"");
      out.print( _ctx );
      out.write("/kho/tonkho\"     class=\"nav-item ");
      out.print( "KHO_TON".equals(activeNav)?"active":"" );
      out.write("\"><span class=\"ni\">&#128230;</span> Tồn kho</a>\n");
      out.write("            <a href=\"");
      out.print( _ctx );
      out.write("/kho/lenhxuat\"   class=\"nav-item ");
      out.print( "KHO_LENH".equals(activeNav)?"active":"" );
      out.write("\"><span class=\"ni\">&#128196;</span> Lệnh xuất</a>\n");
      out.write("\n");
      out.write("        ");
 } else if ("QUAN_LY".equals(_role)) { 
      out.write("\n");
      out.write("            <a href=\"");
      out.print( _ctx );
      out.write("/quanly/dashboard\"               class=\"nav-item ");
      out.print( "QL_DASH".equals(activeNav)?"active":"" );
      out.write("\"><span class=\"ni\">&#128202;</span> Tổng quan</a>\n");
      out.write("            <a href=\"");
      out.print( _ctx );
      out.write("/quanly/dashboard?tab=bophan\"    class=\"nav-item ");
      out.print( "QL_BP".equals(activeNav)?"active":"" );
      out.write("\"><span class=\"ni\">&#127981;</span> Bộ phận</a>\n");
      out.write("            <a href=\"");
      out.print( _ctx );
      out.write("/quanly/dashboard?tab=thongbao\"  class=\"nav-item ");
      out.print( "QL_TB".equals(activeNav)?"active":"" );
      out.write("\"><span class=\"ni\">&#128276;</span> Thông báo</a>\n");
      out.write("            <a href=\"");
      out.print( _ctx );
      out.write("/quanly/dashboard?tab=baocao\"    class=\"nav-item ");
      out.print( "QL_BC".equals(activeNav)?"active":"" );
      out.write("\"><span class=\"ni\">&#128203;</span> Báo cáo</a>\n");
      out.write("\n");
      out.write("        ");
 } else if ("ADMIN".equals(_role)) { 
      out.write("\n");
      out.write("            <a href=\"");
      out.print( _ctx );
      out.write("/admin/accounts\" class=\"nav-item ");
      out.print( "ADMIN_ACC".equals(activeNav)?"active":"" );
      out.write("\"><span class=\"ni\">&#128101;</span> Quản lý tài khoản</a>\n");
      out.write("\n");
      out.write("        ");
 } else if ("DOI_CHIEU".equals(_role)) { 
      out.write("\n");
      out.write("            <a href=\"");
      out.print( _ctx );
      out.write("/doichieu/dashboard\" class=\"nav-item active\"><span class=\"ni\">&#128269;</span> Đối chiếu hàng</a>\n");
      out.write("\n");
      out.write("        ");
 } else if ("TAI_VU".equals(_role)) { 
      out.write("\n");
      out.write("            <a href=\"");
      out.print( _ctx );
      out.write("/taivu/dashboard\" class=\"nav-item active\"><span class=\"ni\">&#128179;</span> Quản lý tài vụ</a>\n");
      out.write("\n");
      out.write("        ");
 } else if ("PHAN_XUONG".equals(_role)) { 
      out.write("\n");
      out.write("            <a href=\"");
      out.print( _ctx );
      out.write("/phanxuong/dashboard\" class=\"nav-item active\"><span class=\"ni\">&#128295;</span> Phân xưởng</a>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("    <div class=\"sidebar-footer\">\n");
      out.write("        <div class=\"user-info\">\n");
      out.write("            <div class=\"avatar\">");
      out.print( _av );
      out.write("</div>\n");
      out.write("            <div>\n");
      out.write("                <div class=\"user-name\">");
      out.print( _hoTen );
      out.write("</div>\n");
      out.write("                <div class=\"user-role\">");
      out.print( _label );
      out.write("</div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <form action=\"");
      out.print( _ctx );
      out.write("/logout\" method=\"get\">\n");
      out.write("            <button type=\"submit\" class=\"btn-logout\">&#8617; Đăng xuất</button>\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("</aside>\n");
      out.write("\n");
      out.write("<div class=\"main-area\">\n");
      out.write("    <header class=\"topbar\">\n");
      out.write("        <div class=\"topbar-title\">");
      out.print( pageTitle );
      out.write("</div>\n");
      out.write("        <div class=\"topbar-right\">\n");
      out.write("            <div class=\"topbar-user\">\n");
      out.write("                <div class=\"avatar\" style=\"width:30px;height:30px;font-size:13px\">");
      out.print( _av );
      out.write("</div>\n");
      out.write("                <span>");
      out.print( _hoTen );
      out.write("</span>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </header>\n");
      out.write("    <div class=\"content\">\n");
      out.write("        ");
 if (_flash != null) { 
      out.write("\n");
      out.write("        <div class=\"flash-msg flash-ok\">&#10003; ");
      out.print( _flash );
      out.write("</div>\n");
      out.write("        ");
 } 
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("<div style=\"padding: 20px;\">\n");
      out.write("    <h2>Bảng điều khiển Thủ kho - Nhập hàng</h2>\n");
      out.write("    <div style=\"background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1);\">\n");
      out.write("        <table style=\"width: 100%; border-collapse: collapse;\">\n");
      out.write("            <thead>\n");
      out.write("                <tr style=\"background: #f1f5f9; text-align: left;\">\n");
      out.write("                    <th style=\"padding: 12px;\">MÃ ĐƠN</th>\n");
      out.write("                    <th>NHÀ CUNG CẤP</th>\n");
      out.write("                    <th>SẢN PHẨM</th>\n");
      out.write("                    <th>SỐ LƯỢNG</th>\n");
      out.write("                    <th style=\"text-align: center;\">THAO TÁC</th>\n");
      out.write("                </tr>\n");
      out.write("            </thead>\n");
      out.write("            <tbody>\n");
      out.write("                ");
 
                List<Map<String,String>> ds = (List<Map<String,String>>) request.getAttribute("dsCho");
                if (ds != null && !ds.isEmpty()) {
                    for (Map<String,String> m : ds) { 
                
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                    <td style=\"padding: 12px;\"><strong>");
      out.print( m.get("maDH") );
      out.write("</strong></td>\n");
      out.write("                    <td>");
      out.print( m.get("tenNCC") );
      out.write("</td>\n");
      out.write("                    <td>");
      out.print( m.get("tenVT") );
      out.write("</td>\n");
      out.write("                    <td style=\"color: blue; font-weight: bold;\">");
      out.print( m.get("soLuong") );
      out.write("</td>\n");
      out.write("                    <td style=\"text-align: center;\">\n");
      out.write("                        <form action=\"");
      out.print( ctx );
      out.write("/kho/nhap\" method=\"post\">\n");
      out.write("                            <input type=\"hidden\" name=\"maDH\" value=\"");
      out.print( m.get("maDH") );
      out.write("\">\n");
      out.write("                            <input type=\"hidden\" name=\"maVT\" value=\"");
      out.print( m.get("maVT") );
      out.write("\">\n");
      out.write("                            <input type=\"hidden\" name=\"sl\" value=\"");
      out.print( m.get("soLuong") );
      out.write("\">\n");
      out.write("                            <button type=\"submit\" style=\"background: #10b981; color: white; border: none; padding: 8px 15px; border-radius: 4px; cursor: pointer;\">\n");
      out.write("                                Xác nhận nhập kho\n");
      out.write("                            </button>\n");
      out.write("                        </form>\n");
      out.write("                    </td>\n");
      out.write("                </tr>\n");
      out.write("                ");
 } } else { 
      out.write("\n");
      out.write("                <tr><td colspan=\"5\" style=\"text-align: center; padding: 40px; color: #64748b;\">Hiện không có đơn hàng nào chờ nhập.</td></tr>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("            </tbody>\n");
      out.write("        </table>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("    </div><!-- end .content -->\n");
      out.write("</div><!-- end .main-area -->\n");
      out.write("</div><!-- end .wrapper -->\n");
      out.write("<script src=\"");
      out.print( request.getContextPath() );
      out.write("/js/main.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
