/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.50
 * Generated at: 2026-04-21 03:28:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"vi\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Đăng nhập – Quản lý kho hàng</title>\n");
      out.write("    <style>\n");
      out.write("        *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }\n");
      out.write("        body {\n");
      out.write("            font-family: 'Segoe UI', Tahoma, sans-serif;\n");
      out.write("            min-height: 100vh;\n");
      out.write("            background: linear-gradient(135deg, #0f172a 0%, #1e3a5f 50%, #0f172a 100%);\n");
      out.write("            display: flex; align-items: center; justify-content: center;\n");
      out.write("        }\n");
      out.write("        .login-box {\n");
      out.write("            background: rgba(255,255,255,0.05);\n");
      out.write("            backdrop-filter: blur(20px);\n");
      out.write("            border: 1px solid rgba(255,255,255,0.10);\n");
      out.write("            border-radius: 20px;\n");
      out.write("            padding: 48px 44px;\n");
      out.write("            width: 420px;\n");
      out.write("            animation: fadeUp .5s ease;\n");
      out.write("        }\n");
      out.write("        @keyframes fadeUp { from{opacity:0;transform:translateY(20px)} to{opacity:1;transform:translateY(0)} }\n");
      out.write("        .logo-wrap  { text-align: center; margin-bottom: 36px; }\n");
      out.write("        .logo-icon  { width:60px;height:60px;background:#2563eb;border-radius:16px;display:flex;align-items:center;justify-content:center;font-size:28px;margin:0 auto 14px; }\n");
      out.write("        .logo-title { color:#f1f5f9;font-size:22px;font-weight:700; }\n");
      out.write("        .logo-sub   { color:#64748b;font-size:13px;margin-top:4px; }\n");
      out.write("        .form-group { margin-bottom: 16px; }\n");
      out.write("        .form-label { color:#94a3b8;font-size:13px;font-weight:500;display:block;margin-bottom:8px; }\n");
      out.write("        .form-input {\n");
      out.write("            width:100%;padding:12px 16px;\n");
      out.write("            background:rgba(255,255,255,0.07);\n");
      out.write("            border:1px solid rgba(255,255,255,0.12);\n");
      out.write("            border-radius:10px;color:#f1f5f9;font-size:14px;outline:none;\n");
      out.write("            transition:border-color .2s,box-shadow .2s;\n");
      out.write("        }\n");
      out.write("        .form-input::placeholder { color:#475569; }\n");
      out.write("        .form-input:focus { border-color:#3b82f6;box-shadow:0 0 0 3px rgba(59,130,246,.18); }\n");
      out.write("        .pass-wrap { position:relative; }\n");
      out.write("        .pass-wrap input { padding-right:44px; }\n");
      out.write("        .pass-toggle { position:absolute;right:14px;top:50%;transform:translateY(-50%);background:none;border:none;cursor:pointer;color:#64748b;font-size:16px; }\n");
      out.write("        .error-msg  { background:rgba(239,68,68,.15);border:1px solid rgba(239,68,68,.3);border-radius:8px;padding:10px 14px;color:#fca5a5;font-size:13px;margin-bottom:16px; }\n");
      out.write("        .btn-login  { width:100%;padding:13px;background:#2563eb;color:#fff;border:none;border-radius:10px;font-weight:700;font-size:15px;cursor:pointer;transition:background .2s;margin-top:8px; }\n");
      out.write("        .btn-login:hover { background:#1d4ed8; }\n");
      out.write("        .demo-box   { margin-top:24px;padding:14px 16px;background:rgba(255,255,255,0.04);border:1px solid rgba(255,255,255,0.08);border-radius:10px; }\n");
      out.write("        .demo-title { color:#475569;font-size:11px;font-weight:600;letter-spacing:1px;text-transform:uppercase;margin-bottom:10px; }\n");
      out.write("        .demo-grid  { display:grid;grid-template-columns:1fr 1fr;gap:6px; }\n");
      out.write("        .demo-item  { padding:6px 8px;border-radius:6px;cursor:pointer;font-size:12px;color:#94a3b8;transition:background .15s; }\n");
      out.write("        .demo-item:hover { background:rgba(255,255,255,0.07); }\n");
      out.write("        .demo-item span  { color:#60a5fa; }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"login-box\">\n");
      out.write("    <div class=\"logo-wrap\">\n");
      out.write("        <div class=\"logo-icon\">&#127981;</div>\n");
      out.write("        <div class=\"logo-title\">Quản lý kho hàng</div>\n");
      out.write("        <div class=\"logo-sub\">Đăng nhập để tiếp tục</div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    ");
 String error = (String) request.getAttribute("error"); 
      out.write("\n");
      out.write("    ");
 if (error != null) { 
      out.write("\n");
      out.write("    <div class=\"error-msg\">&#10060; ");
      out.print( error );
      out.write("</div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    <form action=\"");
      out.print( request.getContextPath() );
      out.write("/login\" method=\"post\">\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("            <label class=\"form-label\">Tên đăng nhập</label>\n");
      out.write("            <input type=\"text\" name=\"username\" class=\"form-input\"\n");
      out.write("                   placeholder=\"Nhập tên đăng nhập\" required autofocus>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("            <label class=\"form-label\">Mật khẩu</label>\n");
      out.write("            <div class=\"pass-wrap\">\n");
      out.write("                <input type=\"password\" name=\"password\" id=\"passInput\" class=\"form-input\"\n");
      out.write("                       placeholder=\"Nhập mật khẩu\" required>\n");
      out.write("                <button type=\"button\" class=\"pass-toggle\" onclick=\"togglePass()\">&#128065;</button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <button type=\"submit\" class=\"btn-login\">Đăng nhập</button>\n");
      out.write("    </form>\n");
      out.write("\n");
      out.write("    <div class=\"demo-box\">\n");
      out.write("        <div class=\"demo-title\">Tài khoản demo</div>\n");
      out.write("        <div class=\"demo-grid\">\n");
      out.write("            <div class=\"demo-item\" onclick=\"fill('admin','123')\"><span>admin</span> · Quản trị</div>\n");
      out.write("            <div class=\"demo-item\" onclick=\"fill('muahang.an','123456')\"><span>muahang.an</span> · Mua hàng</div>\n");
      out.write("            <div class=\"demo-item\" onclick=\"fill('kho.cuong','123456')\"><span>kho.cuong</span> · Kho</div>\n");
      out.write("            <div class=\"demo-item\" onclick=\"fill('quanly.hai','123456')\"><span>quanly.hai</span> · Quản lý</div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("<script>\n");
      out.write("function fill(u,p){\n");
      out.write("    document.querySelector('[name=username]').value=u;\n");
      out.write("    document.querySelector('[name=password]').value=p;\n");
      out.write("}\n");
      out.write("function togglePass(){\n");
      out.write("    const i=document.getElementById('passInput');\n");
      out.write("    i.type=i.type==='password'?'text':'password';\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
